name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to the container registry (Docker Hub, GHCR, etc.)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t QCentroid/qcentroid-base-image-r-base:latest .

      # Push the image to the container registry
      - name: Push Docker Image
        run: |
          docker push QCentroid/qcentroid-base-image-r-base:latest
